Load testing setup for [aftershock](http://www.opb.org/aftershock)

## What's in here?

* `aftershock.jmx` - JMeter test plan, depends on the presence of a `coords.csv` file, that is generated by...
* `sample_coords.r` - Generates a random sample of coordinates within the Oregon state, based on...
* `oregon.shp` and `oregonPopulatedAreas.shp` - Shapefiles with state wide geometry and geometries of select populated areas, as long as their inhabitants.


